os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL swift.qutheory.io/travis)"
script:
  # Build
  - swift build
  - swift build --configuration release
